[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remmapings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts.git/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
